/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'turtle.release+m55he' 
 * Target:  'release+m55he' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HE.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@11.1.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@11.1.0 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.1.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Coroutines@11.1.0 */
#define RTE_RTOS_FreeRTOS_COROUTINE     /* RTOS FreeRTOS Co-routines */
/* ARM::RTOS&FreeRTOS:Event Groups@11.1.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.1.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Message Buffer@11.1.0 */
#define RTE_RTOS_FreeRTOS_MESSAGE_BUFFER /* RTOS FreeRTOS Message Buffers */
/* ARM::RTOS&FreeRTOS:Timers@11.1.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* AlifSemiconductor::Device:SOC Peripherals:DMA@1.3.0 */
#define RTE_Drivers_DMA 1   /* Driver DMA*/
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:USART@1.3.0 */
#define RTE_Drivers_USART0   1           /* Driver UART0 */
#define RTE_Drivers_USART1   1           /* Driver UART1 */
#define RTE_Drivers_USART2   1           /* Driver UART2 */
#define RTE_Drivers_USART3   1           /* Driver UART3 */
#define RTE_Drivers_USART4   1           /* Driver UART4 */
#define RTE_Drivers_USART5   1           /* Driver UART5 */
#define RTE_Drivers_USART6   1           /* Driver UART6 */
#define RTE_Drivers_USART7   1           /* Driver UART7 */


#endif /* RTE_COMPONENTS_H */
